const advance_reading_person = [
    ["From", "To", "Type"],
    ["A Concept Diagram For RWOT Identity Terms", "Unknown Author", "Unknown Type"],
    ["A cool hack with XDI graphs, blockstore, link contracts, and cryptographic identifiers", "Markus Sabadello", "Authored"],
    ["A Demonstration of the Veres One Blockchain", "Unknown Author", "Unknown Type"],
    ["A DID for Every Thing: Driving Event Data Chain", "Carsten Stöcker", "Authored"],
    ["A DID for Every Thing: Driving Event Data Chain", "Michael Rüther", "Authored"],
    ["A New Approach to Social Key Recovery", "Christopher Allen", "Authored"],
    ["A New Approach to Social Key Recovery", "Mark Friedenbach", "Authored"],
    ["A Notebook Workbench for SSI", "Eric Welton", "Authored"],
    ["A Primer on Self-Sovereign Identity", "Unknown Author", "Unknown Type"],
    ["A Primer on the Veres One Decentralized Identifier Blockchain", "Unknown Author", "Unknown Type"],
    ["A Public Web of Trust of Public Identities", "Unknown Author", "Unknown Type"],
    ["A Self-Sovereign Identity Architecture", "Unknown Author", "Unknown Type"],
    ["A Self-Sovereign Identity Framework/Thought Model proposal", "Rieks Joosten", "Authored"],
    ["A Short Primer for Decentralized Identifiers", "Unknown Author", "Unknown Type"],
    ["A Technology‐Free Definition of Self‐Sovereign Identity", "Unknown Author", "Unknown Type"],
    ["A Trustless Web-of-Trust – establishing identity uniqueness", "Unknown Author", "Unknown Type"],
    ["A Verifiable Claims Primer", "Unknown Author", "Unknown Type"],
    ["Activitypub decentralized distributed", "Unknown Author", "Unknown Type"],
    ["Addressing Global/Local Barriers to Adoption of Decentralized Identity Systems", "Unknown Author", "Unknown Type"],
    ["Advanced Web of Trust Concepts", "Christopher Allen", "Authored"],
    ["Agent to Agent Communication Protocol Overview: Addressing principles and concerns", "Unknown Author", "Unknown Type"],
    ["Aligning Signature Formats", "Unknown Author", "Unknown Type"],
    ["Aligning SSI with European Union identity legislation (aka eIDAS Regulation)", "Nacho Alamillo", "Authored"],
    ["Aligning SSI with European Union identity legislation (aka eIDAS Regulation)", "Santi Casas", "Authored"],
    ["Alternative Futures: Framework for Identity Scenarios", "Unknown Author", "Unknown Type"],
    ["Anonymous Credentials in Sovrin", "Unknown Author", "Unknown Type"],
    ["Applying POLA to User Interaction", "Bill Tulloh", "Authored"],
    ["Architectural Layering for Decentralized Identification", "Unknown Author", "Unknown Type"],
    ["Architecture of proof-of-stake blockchain that doesn’t have native coin", "Unknown Author", "Unknown Type"],
    ["Assist underrepresented groups when entering the labour market through self sovereign identity", "Karolin Siebert", "Authored"],
    ["Attempts at common terminology for Digital Identity systems", "Christian Lundkvist", "Authored"],
    ["Attention as a Source of Scarcity for Decentralized Identity Systems", "Maciej Laskus", "Authored"],
    ["Attribute Based Credentials", "Unknown Author", "Unknown Type"],
    ["Authorities vs. Peers: Pain Points in Security", "Christopher Allen", "Authored"],
    ["Authorities vs. Peers: Pain Points in Security", "Shannon Appelcline", "Authored"],
    ["Avoiding Confused Deputy Attack Using Capabilities", "Tyler Close", "Authored"],
    ["Beyond Identity Cards to Distributed Identity", "Unknown Author", "Unknown Type"],
    ["BFTKV", "Unknown Author", "Unknown Type"],
    ["BFTKV DID Method Specification", "Unknown Author", "Unknown Type"],
    ["Binding Identity in a Decentralized System", "Wayne Thayer", "Authored"],
    ["Biometric transaction signing on blockchain", "Unknown Author", "Unknown Type"],
    ["BIP32-Ed25519 Hierarchical Deterministic Keys over a Non-linear Keyspace", "Unknown Author", "Unknown Type"],
    ["Blockcerts -- where we are, and what\"s next", "Unknown Author", "Unknown Type"],
    ["Blockcerts and Open Badges signature alignment", "Unknown Author", "Unknown Type"],
    ["Blockchain Attestation Taxonomies", "Unknown Author", "Unknown Type"],
    ["Blockchain Based Digital Signatures: Admissibility and Enforceability", "Unknown Author", "Unknown Type"],
    ["Blockchain Extensions for Linked Data Signatures", "Unknown Author", "Unknown Type"],
    ["Blockchain for capital markets", "Unknown Author", "Unknown Type"],
    ["Blockchain tech opportunities in the Web-of-Trust", "Peter Todd", "Authored"],
    ["Blockchain Technologies Feature Analysis", "Unknown Author", "Unknown Type"],
    ["Blockchain Timestamps Unnecessary In Proof-of-Work?", "Unknown Author", "Unknown Type"],
    ["Blockchain-based Trust for Software Components", "Sean Gilligan", "Authored"],
    ["Blockstack Rules and Support for Multiple Blockchains", "Unknown Author", "Unknown Type"],
    ["Booting a Web of Sovereignty with a Decentralized Social App", "Unknown Author", "Unknown Type"],
    ["Bringing the Dependencies of a BTCR Wallet to the Swift Ecosystem", "Wolf McNally", "Authored"],
    ["BTCR DIDs and DDOs", "Unknown Author", "Unknown Type"],
    ["Building a web of trust for decentralized e-commerce platforms", "Michael Folkson", "Authored"],
    ["Can Curation Markets establish Sustainable Technology Commons?", "Unknown Author", "Unknown Type"],
    ["CapAuth", "Unknown Author", "Unknown Type"],
    ["Certificate chains for DID-based self-sovereign identities", "Unknown Author", "Unknown Type"],
    ["CHIME National Patient ID Challenge", "Unknown Author", "Unknown Type"],
    ["Clues", "Unknown Author", "Unknown Type"],
    ["Collegial Certification Works", "Unknown Author", "Unknown Type"],
    ["Creating a Humanized Internet", "Unknown Author", "Unknown Type"],
    ["Credential Providers for Signing Application Requests", "Unknown Author", "Unknown Type"],
    ["Credentials and Correlation", "Jack Poole", "Authored"],
    ["Credit-based Reputations for Identity Management with Blockchain and Flow Networks", "Unknown Author", "Unknown Type"],
    ["Cryptocurrency wallets as a form of Functional Identity", "Unknown Author", "Unknown Type"],
    ["Cryptographic and Data Modeling Requirements from RWoT", "Unknown Author", "Unknown Type"],
    ["Current Status of the DID Specification", "Amy Guy", "Authored"],
    ["Current Status of the DID Specification", "Dmitri Zagidulin", "Authored"],
    ["Data Value Realisation: Control, Commons & Ownership", "Katryna Dow", "Authored"],
    ["DClaims News", "Unknown Author", "Unknown Type"],
    ["Dealing with private key loss or compromise in digital identity systems", "Christian Lundkvist", "Authored"],
    ["Decentralized Digital Identity: The Book", "Alex Preukschat", "Authored"],
    ["Decentralized Digital Identity: The Book", "Drummond Reed", "Authored"],
    ["Decentralized Attestations Storage Challenges", "Unknown Author", "Unknown Type"],
    ["Decentralized Authentication with Blockchain Auth", "Ryan Shea", "Authored"],
    ["Decentralized Cooperation needs Decentralized Reputation", "Noah Thorp", "Authored"],
    ["Decentralized Error Reporting", "Unknown Author", "Unknown Type"],
    ["Decentralized Identifier Tooling", "Unknown Author", "Unknown Type"],
    ["Decentralized Identifier Tooling API", "Unknown Author", "Unknown Type"],
    ["Decentralized Identifiers (DIDs) and Decentralized Identity Management (DIDM)", "Unknown Author", "Unknown Type"],
    ["Decentralized Identities and eIDAS", "Unknown Author", "Unknown Type"],
    ["Decentralized Identities for the Cannabis Industry", "Unknown Author", "Unknown Type"],
    ["Decentralized Identity – Hub Authentication & Message Encryption", "Unknown Author", "Unknown Type"],
    ["Decentralized Identity Fee Market", "Unknown Author", "Unknown Type"],
    ["Decentralized Identity Satoshi Style", "Unknown Author", "Unknown Type"],
    ["Decentralized Interfaces and the Request", "Unknown Author", "Unknown Type"],
    ["Decentralized Key Management System", "Unknown Author", "Unknown Type"],
    ["Decentralized Trust for Software Components", "Sean Gilligan", "Authored"],
    ["Declaration of Identity", "Unknown Author", "Unknown Type"],
    ["Designing an Educational Credentialing Ecosystem", "Kim Hamilton Duffy", "Authored"],
    ["Designing an Educational Credentialing Ecosystem", "J. Philipp Schmidt", "Authored"],
    ["Designing an Educational Credentialing Ecosystem", "Joe Andrieu", "Authored"],
    ["Designing Identity for People & Places", "Unknown Author", "Unknown Type"],
    ["Designing Trust in Identity Systems", "Bentley Farrington", "Authored"],
    ["Designing Trust in Identity Systems", "Bart Suichies", "Authored"],
    ["Dex: Deterministic Predicate Expressions ", "Unknown Author", "Unknown Type"],
    ["DID (Decentralized Identifier) Specification", "Unknown Author", "Unknown Type"],
    ["DID Auth", "Unknown Author", "Unknown Type"],
    ["DID Auth: Scope", "Unknown Author", "Unknown Type"],
    ["DID for the 3D Web", "Unknown Author", "Unknown Type"],
    ["DID Method Specifications / BTCR and PGPR", "Unknown Author", "Unknown Type"],
    ["DID Names", "Unknown Author", "Unknown Type"],
    ["DID Namespace Records", "Drummond Reed", "Authored"],
    ["DID Primer", "Unknown Author", "Unknown Type"],
    ["DID Primer Extended", "Unknown Author", "Unknown Type"],
    ["DID Resolution Topics", "Unknown Author", "Unknown Type"],
    ["DID-Auth Protocol", "Unknown Author", "Unknown Type"],
    ["did:erc725 method", "Unknown Author", "Unknown Type"],
    ["DIDDoc Conventions for Interoperability", "Unknown Author", "Unknown Type"],
    ["DIDs (Decentralized IDentifiers): Solving the Root Identity Problem", "Unknown Author", "Unknown Type"],
    ["DIDs and Personal Data Storage for Children", "Unknown Author", "Unknown Type"],
    ["DIDs In DPKI", "Unknown Author", "Unknown Type"],
    ["Digital Contraception", "Mitzi László", "Authored"],
    ["Different Models for Trust", "Kaliya Young", "Authored"],
    ["Digital Identity for the Homeless", "Mike Varley", "Authored"],
    ["Digital Identity for the Homeless", "Matthew Wong", "Authored"],
    ["Digital Trust Protocol", "Carsten Keutmann", "Authored"],
    ["Digital Trust Protocol", "Tim Pastoor", "Authored"],
    ["Distributed identities as a EU cross-border identity infrastructure", "Unknown Author", "Unknown Type"],
    ["Distributed Identity Management ­ Verifiable Claims Exchange Via Agents", "Unknown Author", "Unknown Type"],
    ["Distributed Identity, Distributed Self", "Unknown Author", "Unknown Type"],
    ["Distributed multi-ledger model for financial industry", "Pavel Kravchenko", "Authored"],
    ["Distributed Receptor-Based Computing", "Arthur Brock", "Authored"],
    ["Distributed Reputation Systems Using Blockchain Records", "Unknown Author", "Unknown Type"],
    ["Distributed Trust Systems and the Kenyesian Beauty Contest", "Joel Dietz", "Authored"],
    ["DKMS layers diagram", "Unknown Author", "Unknown Type"],
    ["Engineering Privacy for Verified Credentials: In Which We Describe Data Minimization, Selective Disclosure and Progressive Trust", "Unknown Author", "Unknown Type"],
    ["Erik Anderson-USE CASE story", "Unknown Author", "Unknown Type"],
    ["EU Digital Signature vs. VC Model", "Luca Boldrin", "Authored"],
    ["EU-General-Data-Protection Regulation-Self-Sovereign Identifiers", "Unknown Author", "Unknown Type"],
    ["Exploring adoptation of VC sharing to provide value today", "Snorre Lothar von Gohren Edwin", "Authored"],
    ["Exploring Browser Web of Trust Use Cases", "Unknown Author", "Unknown Type"],
    ["Financing a Self-sovereign Technology Stack", "Adrian Gropper", "Authored"],
    ["First Encounters with PGP", "Kiara Robles", "Authored"],
    ["First XDI Link Contract between \"btcr\" DID and \"sov\" DID", "Unknown Author", "Unknown Type"],
    ["Fit for Purpose Blockchains", "Unknown Author", "Unknown Type"],
    ["Five Mental Models of Identity", "Unknown Author", "Unknown Type"],
    ["Fostering the resilience of an ecosystem of workers through regulated decentralized reputation", "Unknown Author", "Unknown Type"],
    ["Framework for the Comparison of Identity Systems", "Unknown Author", "Unknown Type"],
    ["From Identity to Refugee Status Determination", "Unknown Author", "Unknown Type"],
    ["Functional Identity Primer", "Unknown Author", "Unknown Type"],
    ["GDPR and the right to erasure", "Oleg Burundukov", "Authored"],
    ["GDPR and the right to erasure", "Eduardo Moraes de Morais", "Authored"],
    ["Generating Actionable Intelligence with Wallets and Agents for People & Places", "Sam Chase", "Authored"],
    ["Generating Actionable Intelligence with Wallets and Agents for People & Places", "Joni McKervey", "Authored"],
    ["Glossary of Terms", "Unknown Author", "Unknown Type"],
    ["Handshake", "Boyma Fahnbulleh", "Authored"],
    ["hashed-PII-Question", "Unknown Author", "Unknown Type"],
    ["HIE of One Loop: A Patient-Controlled Independent Health Record", "Unknown Author", "Unknown Type"],
    ["Higher-Definition Digital Identity", "Shaun Conway", "Authored"],
    ["Hierarchical Deterministic Keys: BIP32 & Beyond", "Christopher Allen", "Authored"],
    ["Hierarchical Deterministic Keys: BIP32 & Beyond", "Shannon Appelcline", "Authored"],
    ["How Do We Bootstrap the Web of Trust for VC", "Matt Stone", "Authored"],
    ["How Do We Bootstrap the Web of Trust for VC", "Dan Burnett", "Authored"],
    ["Humanity\"s API - solving Fermi paradox", "Bohdan Andriyiv", "Authored"],
    ["Hub Asset Access Control System - Intent", "Unknown Author", "Unknown Type"],
    ["Hypercerts: Blockcerts Revocation Improvements", "Unknown Author", "Unknown Type"],
    ["I see graphs everywhere. On the importance of graphs and graph analysis way of thinking.", "Bohdan Andriyiv", "Authored"],
    ["ID-Blockchain : an initiative towards privacy preserving blockchain based identity", "Unknown Author", "Unknown Type"],
    ["IDEAS", "Unknown Author", "Unknown Type"],
    ["Identifying stakeholders\" challenges in the digital economy", "Unknown Author", "Unknown Type"],
    ["Identities for Moving Things", "Unknown Author", "Unknown Type"],
    ["Identity and decentralised communications", "Unknown Author", "Unknown Type"],
    ["Identity as Linked Data on Immutable Ledgers", "Unknown Author", "Unknown Type"],
    ["Identity Containers. Blockchain implementation proposal with DIDs & ERC725", "Alex Puig", "Authors"],
    ["Identity Forking and Federated Reputation", "Unknown Author", "Unknown Type"],
    ["Identity Hub Permissions/Authorization", "Unknown Author", "Unknown Type"],
    ["Identity is a Phenomenon, Not a Property", "Unknown Author", "Unknown Type"],
    ["Identity Management IDSEC", "Unknown Author", "Unknown Type"],
    ["Identity Manager Concept", "André Cruz", "Authored"],
    ["Identity Manager Concept", "João Santos", "Authored"],
    ["Identity Manager Concept", "Pedro Teixeira", "Authored"],
    ["Identity Manager Specification", "Adin Schmahmann", "Authored"],
    ["Identity Manager Specification", "André Cruz", "Authored"],
    ["Identity Manager Specification", "Pedro Teixeira", "Authored"],
    ["Identity System Essentials", "Unknown Author", "Unknown Type"],
    ["Identity System for Immersive and Ambient Computing", "Unknown Author", "Unknown Type"],
    ["Identity, Guidance and Situational Awareness", "Matthew Schutte", "Authored"],
    ["Immutable Me", "Unknown Author", "Unknown Type"],
    ["Implementing of threshold schemes", "Daan Sprenkels", "Authored"],
    ["Integrating Identity silos via address books", "Unknown Author", "Unknown Type"],
    ["Introductory Capability DHT Concept", "James Foley", "Authored"],
    ["IPLD as a general pattern for DID documents", "Unknown Author", "Unknown Type"],
    ["Is a Decentralized Collective Identity Possible?", "Unknown Author", "Unknown Type"],
    ["Is the Universe a blockchain? A cryptographic model of the Universe.", "Bohdan Andriyiv", "Authored"],
    ["Journalistic use-cases for SSI: signatures, verified claims, and canonical-text registries", "Juan Caballero", "Authored"],
    ["Journalistic use-cases for SSI: signatures, verified claims, and canonical-text registries", "Jefferson Sofarelli", "Authored"],
    ["Joram 2.0.0", "Joe Andrieu", "Authored"],
    ["Joram 2.0.0", "Bob Clint", "Authored"],
    ["JXD Examples", "Unknown Author", "Unknown Type"],
    ["Key revocation of lost and stolen keys", "Martin Koeppelmann", "Authored"],
    ["Key Transparency for End Users", "Joseph Bonneau", "Authored"],
    ["Knowing When Your Digital Identity Has Been Compromised", "Justin Newton", "Authored"],
    ["Legal Frameworks for Humanity in the Digital Age", "Elizabeth M. Renieris", "Authored"],
    ["Legalizing Identity Protocols for the United Nations 16.9", "Unknown Author", "Unknown Type"],
    ["Lightning Network and Web of Trust", "Joseph Poon", "Authored"],
    ["Linked Local Names: An Overview", "Christopher Allen", "Authored"],
    ["libp2p for DID Authentication and the exchange of Verifiable Credentials", "jonnycrunch", "Authored"],
    ["Magenc Magnet URIs: Secure Object Permanence for the Web", "Unknown Author", "Unknown Type"],
    ["Measuring Trust", "Unknown Author", "Unknown Type"],
    ["Minimal implementation of verifiable credentials for a community of practice use case on an agent-centric distributed platform", "Jakub Lanc", "Authored"],
    ["Modern PKI: Identity Assertions Forming Trust Networks", "Duke Dorje", "Authored"],
    ["More control for Identity Holders", "Unknown Author", "Unknown Type"],
    ["Multi-Factor Attribute Trust", "Will Abramson", "Authored"],
    ["Multiformat Superfriends (The Multibase, Multihash, and Hashlink Specifications)", "Manu Sporny", "Authored"],
    ["Multiformat Superfriends (The Multibase, Multihash, and Hashlink Specifications)", "Ganesh Annan", "Authored"],
    ["No Secure Protocol = No Sovereign Identity", "Unknown Author", "Unknown Type"],
    ["Nobody REALLY Trusts the Blockchain", "Unknown Author", "Unknown Type"],
    ["Not-a-Bot: A Use Case for Decentralized Identity using Proximity Verification to generate a Web of Trust", "Unknown Author", "Unknown Type"],
    ["Authored by a team", "Oliver Terbu", "Authored"],
    ["OIDC Profile for SSI", "Andres Junge", "Authored"],
    ["On interpersonal data", "Philip Sheldrake", "Authored"],
    ["Open Badges as Verifiable Claims", "Unknown Author", "Unknown Type"],
    ["Open time stamps merkle tree", "Unknown Author", "Unknown Type"],
    ["Open TLS", "Unknown Author", "Unknown Type"],
    ["Open Verifiable Data to Drive the Digital Economy", "Unknown Author", "Unknown Type"],
    ["openbadges prototypes action items 2018", "Unknown Author", "Unknown Type"],
    ["OpenTimestamps: Scalable, Trustless, Distributed Timestamping with Bitcoin", "Unknown Author", "Unknown Type"],
    ["Owned vs. Unowned Claims and Self-Sovereign Identity", "Unknown Author", "Unknown Type"],
    ["Peer Attestation of Identity in the Real World", "Unknown Author", "Unknown Type"],
    ["Peer to Peer DIDs", "Brent Zundel", "Authored"],
    ["Peer-to-peer DID Specification", "Brent Zundel", "Authored"],
    ["Personal Levels of Assurance (PLOA)", "Unknown Author", "Unknown Type"],
    ["Petnames for Self Sovereign", "Unknown Author", "Unknown Type"],
    ["PKI Tools in EVM-based Blockchains", "Christian Lundkvist", "Authored"],
    ["Plurality of Provenance in Distributed Identity", "Unknown Author", "Unknown Type"],
    ["Portable Reputation Toolkit", "Unknown Author", "Unknown Type"],
    ["Privacy Preserving Web Identity Architectures", "Unknown Author", "Unknown Type"],
    ["Progressive Trust", "Christopher Allen", "Authored"],
    ["Project Vouch - A decentralized identity network based on public attestation, reputation, and approval of identity attributes", "Unknown Author", "Unknown Type"],
    ["Proof of Key Ownership with OpenID Connect Self-Issued Identities", "Michael B. Jones", "Authored"],
    ["Providing Decentralized Identity to the most vulnerable populations", "Jeremi Joslin", "Authored"],
    ["Providing Decentralized Identity to the most vulnerable populations", "Greg Martel", "Authored"],
    ["Providing Decentralized Identity to the most vulnerable populations", "Hailey Park", "Authored"],
    ["Proposed collaboration on open standards for data wallet", "Unknown Author", "Unknown Type"],
    ["PSDAD - Data Format with Secure Semantics", "Sandro Hawke", "Authored"],
    ["PSDAD Specification", "Sandro Hawke", "Authored"],
    ["Querying Bitcoin blockchain for BTCR support", "Kulpreet Singh", "Authored"],
    ["Questions around key management for digital identity systems", "Unknown Author", "Unknown Type"],
    ["Re-inventing Incentive Structures Using DID and Microtransactions", "Yancy Ribbens", "Unknown Type"],
    ["Real life application of WoT", "Alicia Carmona", "Authored"],
    ["Rebooting Web of Trust Position MindMap", "Unknown Author", "Unknown Type"],
    ["Rebooting-the-web-of-trust Identity, Property and Simulation", "Unknown Author", "Unknown Type"],
    ["RebootingWebOfTrust User Story & Tech Concept", "Unknown Author", "Unknown Type"],
    ["Recent happenings with Linked Data Capabilities", "Unknown Author", "Unknown Type"],
    ["Recommendations for Decentralized Key Management Systems", "Unknown Author", "Unknown Type"],
    ["Recovery strategy for user-controlled keys for self-sovereign identity", "Unknown Author", "Unknown Type"],
    ["Reputation proofs", "Unknown Author", "Unknown Type"],
    ["Rethinking Priorities: Should Identity Systems Divide or Unite People?", "Bryan Ford", "Authored"],
    ["RWoT proposals and modern portable secure hardware", "Unknown Author", "Unknown Type"],
    ["RWOT local chapters", "Bohdan Andriyiv", "Authored"],
    ["Scaling a BFT Consensus Protocol for Identity", "Unknown Author", "Unknown Type"],
    ["Schnorr Signatures: An Overview", "Christopher Allen", "Authored"],
    ["Schnorr Signatures: An Overview", "Shannon Appelcline", "Authored"],
    ["Scoped Presentation Request on Verifiable Credentials", "Unknown Author", "Unknown Type"],
    ["Secret Handshake : Key Exchange as a Capability System", "Dominic Tarr", "Authored"],
    ["Secure Crypto-Wallet Introductions", "Unknown Author", "Unknown Type"],
    ["Secure Naming on the Blockchain", "Muneeb Ali", "Authored"],
    ["Security Considerations of Shamir\"s Secret Sharing", "Unknown Author", "Unknown Type"],
    ["Selective Disclosure of Identity with Hierarchical Deterministic Keys ", "Ryan Shea", "Authored"],
    ["Self-Sovereign Compliance: Use case for DIDs and VCs", "Unknown Author", "Unknown Type"],
    ["Self-Sovereign Identity Framework/Thought Model", "Unknown Author", "Unknown Type"],
    ["Slepak’s Triangle", "Unknown Author", "Unknown Type"],
    ["Social Key Recovery", "Hank Chiu", "Unknown Type"],
    ["Social Key Recovery", "Hankuan Yu", "Authored"],
    ["Social Key Recovery", "Justin Lin ", "Authored"],
    ["Social Key Recovery", "Jon Tsai", "Authored"],
    ["SLIP-0039: Shamir\"s Secret-Sharing for Mnemonic Codes", "Trezor", "Team Author"],
    ["#SSI20XX - Model Use-Case Definitions and Implementation", "Martin Riedel", "Authored"],
    ["Sovereign Identity Model for Digital Ecologies", "Unknown Author", "Unknown Type"],
    ["Sovereign Identity Namespaces", "Unknown Author", "Unknown Type"],
    ["Sovrin: digital identities in the blockchain era", "Unknown Author", "Unknown Type"],
    ["Standards for Agency and Decentralized Information Governance - Early Experience", "Unknown Author", "Unknown Type"],
    ["Staying Anonymous With DIDs", "David Stark", "Authored"],
    ["Structures of Identity", "Ethan Brown", "Unknown Type"],
    ["Tensions related to identity and community regulation", "Matthew Schutte", "Authored"],
    ["The Current Status of the DID Specification", "Unknown Author", "Unknown Type"],
    ["The DID Family of Specifications", "Unknown Author", "Unknown Type"],
    ["The Horcrux Protocol", "Unknown Author", "Unknown Type"],
    ["The Horcrux protocol: Biometric credentials as high-privacy verifiable claims", "Unknown Author", "Unknown Type"],
    ["The IP Blockchain: enhancing global responsiveness to infectious disease outbreaks", "Unknown Author", "Unknown Type"],
    ["The Naming of Things", "Matthew Schutte", "Authored"],
    ["The Need For A Generic Thin Client Protocol", "Greg Slepak", "Authored"],
    ["The Path to Self-Sovereign Identity", "Unknown Author", "Unknown Type"],
    ["The PGP Paradigm", "Phil Zimmerman", "Authored"],
    ["The PGP Paradigm", "Jon Callas", "Authored"],
    ["The Political Economy of Naming - RWoT Fall 2018", "Unknown Author", "Unknown Type"],
    ["The Role of Standards in Accelerating Innovation", "Unknown Author", "Unknown Type"],
    ["The Three Primary Roles in the Sovrin Web of Trust Model", "Unknown Author", "Unknown Type"],
    ["The Universal Ledger Agent: a Logical Result of Rabobank\"s Journey in Blockchain-based self-sovereign identity", "David Lamers", "Authored"],
    ["The Untimely Death of SSI", "Michael Shea", "Authored"],
    ["The United Humans - can it really work?", "Bohdan Andriyiv", "Authored"],
    ["The Veres One Blockchain", "Unknown Author", "Unknown Type"],
    ["The Veres One DID Method", "Unknown Author", "Unknown Type"],
    ["Towards a Sustainable Technology Commons", "Unknown Author", "Unknown Type"],
    ["Towards a User Interface for Selectively Revealing Fine-Grained Personal Information to Transaction Counterparties", "Unknown Author", "Unknown Type"],
    ["Towards a user-centered web of trust", "Unknown Author", "Unknown Type"],
    ["Towards Proof-of-Person", "Unknown Author", "Unknown Type"],
    ["Trust Exchange: An Architecture for a Permanent Open Trust Network", "Harlan T. Wood", "Authored"],
    ["Trust for Security and Security for Trust", "Unknown Author", "Unknown Type"],
    ["Trust Objects: Enabling advanced reputation services in the Web of Trust", "Unknown Author", "Unknown Type"],
    ["Trust-i-ness", "Unknown Author", "Unknown Type"],
    ["Universal DID Operations", "Markus Sabadello", "Authored"],
    ["Universal DID Operations", "Nader Helmy", "Authored"],
    ["Universal ID Framework", "Shigeya Suzuki", "Authored"],
    ["Usability and Multiplicity in Global Identity Management", "Unknown Author", "Unknown Type"],
    ["Using blockchain to store academic accreditations", "Unknown Author", "Unknown Type"],
    ["Using Immutable Data Objects ", "Ken Ebert", "Authored"],
    ["UX and Use Cases", "Unknown Author", "Unknown Type"],
    ["Veres One DID Method Specification", "Unknown Author", "Unknown Type"],
    ["Verifiable Claims and Web of Trust", "Unknown Author", "Unknown Type"],
    ["Verifiable Claims for Postal Address", "Moses Ma", "Authored"],
    ["Verifiable Claims of Impact", "Unknown Author", "Unknown Type"],
    ["Verifiable Credentials Primer", "Unknown Author", "Unknown Type"],
    ["Verifiable Displays", "Unknown Author", "Unknown Type"],
    ["Verifiable Displays: secure presentation of Verifiable Credentials in HTML", "Bohdan Andriyiv", "Authored"],
    ["Verifiable Offline Credentials", "Unknown Author", "Unknown Type"],
    ["Visa Really", "Unknown Author", "Unknown Type"],
    ["W3C Strong Authentication and Identity Workshop Report (DRAFT)", "Unknown Author", "Unknown Type"],
    ["Web of Pragmatics", "Unknown Author", "Unknown Type"],
    ["Web of Trust with Blockchain IDs", "Unknown Author", "Unknown Type"],
    ["Web Reputation Systems and the Real World", "Randy Farmer", "Authored"],
    ["Web Reputation Systems and the Real World", "Bryce Glass", "Authored"],
    ["What and Who Is In Your Wallet?", "Alberto Elias", "Unknown Type"],
    ["Where\"s the UX?", "Unknown Author", "Unknown Type"],
    ["Why webs of trust work, even the PGP one?", "Bohdan Andriyiv", "Authored"],
    ["White Papers, Specifications & Proofs of Concept", "Christopher Allen", "Authored"],
    ["XDI Graphs in IPFS", "Unknown Author", "Unknown Type"],
    ["XDI Link Contracts: An Overview", "Drummond Reed", "Authored"],
    ["XDI Verifiable Claims and Link Contracts", "Unknown Author", "Unknown Type"],
    ["Zero Trust Computing with DIDs and DADs", "Unknown Author", "Unknown Type"],
    ["Zero-knowledge proofs in identity systems", "Jordi Baylina", "Authored"],
    ["Zero-knowledge proofs in identity systems", "David Suarez", "Authored"]
];
